"""Copy registered-run LaTeX artifacts into dissertation/generated/.

Every experiment in experiments/manifest.toml that has an ``export_path``
gets its exported ``tables/*.tex`` (and any PNG figures) mirrored to
``dissertation/generated/<experiment-id>/``, each file prefixed with a
provenance header naming the experiment, run ids, and commit. Chapters
``\\input`` these files instead of hand-typing numbers, so a re-run plus a
refresh updates the document and nothing can silently drift from the run
it claims to report.

Usage:  python scripts/refresh_dissertation_assets.py
        (or: make -C dissertation assets)
"""

from __future__ import annotations

import shutil
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = REPO_ROOT / "experiments" / "manifest.toml"
TARGET_ROOT = REPO_ROOT / "dissertation" / "generated"


def provenance_header(experiment: dict) -> str:
    commit = str(experiment.get("commit_sha", "?"))[:12]
    lines = [
        "% AUTO-GENERATED by scripts/refresh_dissertation_assets.py -- do not edit by hand.",
        f"% Experiment: {experiment.get('id', '?')} | runs {experiment.get('run_ids', '?')} | commit {commit}",
    ]
    dataset = experiment.get("dataset", {})
    if dataset:
        lines.append(f"% Dataset: {dataset.get('path', '?')} | sha256 {str(dataset.get('sha256', '?'))[:12]}")
    return "\n".join(lines) + "\n"


def refresh() -> int:
    with MANIFEST.open("rb") as handle:
        manifest = tomllib.load(handle)

    copied = 0
    for experiment in manifest.get("experiments", []):
        export_path = experiment.get("export_path")
        if not export_path:
            continue
        source = REPO_ROOT / export_path
        experiment_id = experiment["id"]
        if not source.exists():
            print(f"skip {experiment_id}: export path missing ({export_path})")
            continue
        target = TARGET_ROOT / experiment_id
        target.mkdir(parents=True, exist_ok=True)
        header = provenance_header(experiment)
        for tex in sorted(source.glob("tables/*.tex")):
            (target / tex.name).write_text(header + tex.read_text(encoding="utf-8"), encoding="utf-8")
            copied += 1
        for figure in sorted(source.glob("*.png")):
            shutil.copy2(figure, target / figure.name)
            copied += 1
        print(f"refreshed {experiment_id}: -> dissertation/generated/{experiment_id}/")

    if copied == 0:
        print("Nothing refreshed: no manifest experiment has an existing export_path.")
        return 1
    print(f"{copied} artifact(s) refreshed. Include with e.g. \\input{{generated/<id>/leaderboard}}")
    return 0


if __name__ == "__main__":
    sys.exit(refresh())
